#!/bin/sh
[ "$1" = "-" ] && {
  pipe=0
}
[ -e "$1" -o "$pipe" ] || {
  shcat << EOF
$1 is not present...
EOF
  exit 1
}
case "$2" in
  ("UTF8"|"UTF8s")
    #printf '\rProcessing... This will take awhile... Sorry...\r'
    if [ ! "$pipe" ]; then
      trim_all $(od -v -t o1 -An < "$1") | utf8 "$2"
    else
      trim_all $(od -v -t o1 -An) | utf8 "$2"
    fi
  ;;
  ("OCT"*)
    if [ ! "$pipe" ]; then
      #octdump="$(od -v -t o1 -An < "$1")"
      od -v -t o1 -An < "$1"
    else
      #octdump="$(od -v -t o1 -An)"
      od -v -t o1 -An
    fi
    exit 0
  ;;
  ("HEX"*)
    if [ ! "$pipe" ]; then
      #hexdump="$(od -v -t x1 -An < "$1")"
      od -v -t x1 -An < "$1"
    else
      #hexdump="$(od -v -t x1 -An )"
      od -v -t x1 -An -
    fi
    #hexdump="$(trim_all "$hexdump")"
    printf 'Processing... This will take awhile... Sorry...\r'
    # this is easier than converting from octal with printf
    # as each octal number has to be prepended with a 0
    # then fed through printf '%x ' # %X for capital
    ##
    # if compatibility is an issue using printf instead is likely better
  ;;
  ("POSIX")
    if [ ! "$pipe" ]; then
      shcat < "$1"; exit 0
    else
      shcat; exit 0
    fi
  ;;
esac
